title: TweetSkyBridge
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
url: "https://jonathanburgess.dev"
baseurl: "/tweetskybridge"
minima:
  hide_site_feed_link: true
  skin: dark
  social_links:
    - title: BlueSky
      icon: bluesky
      url: "https://bsky.app/profile/jonathanburgess.dev"
    - title: GitHub
      icon: github
      url: "https://github.jonathanburgess.dev"
    - title: LinkedIn
      icon: linkedin
      url: "https://linkedin.jonathanburgess.dev"
author: Jonathan Burgess
email: "mail@jonathanburgess.dev"